name 'git_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures git_test'
long_description 'Installs/Configures git_test'
version '0.1.0'

depends 'git', '~> 4.3'
depends 'docker', '~> 2.0'